#! /bin/bash


# echo '{"games":[], "newGameId":1}' > data/games.json
# echo '{}' > data/session.json

PROJECT="/Users/souravdas/practice/js/assigments/scotland-yard-byomkesh"
cp ./qa.env "${PROJECT}/.env"


(cd $PROJECT; npm start)
